NOTHING_NUM = 0
SNAKEHEAD_NUM = 1
SNAKEBODY_NUM = 2
FOOD_NUM = 3

NUM_X_GRID = 20
NUM_Y_GRID = 20

X_GRID_SIZE = 30
Y_GRID_SIZE = 30

WIN_WIDTH = X_GRID_SIZE * NUM_X_GRID
WIN_HEIGHT = Y_GRID_SIZE * NUM_Y_GRID
