WALL_NUM = 0
SNAKE_BODY_NUM = 1
SNAKE_HEAD_NUM = 2
NOTHING_NUM = 5
FOOD_NUM = 10

NUM_X_GRID = 20
NUM_Y_GRID = 20

X_GRID_SIZE = 30
Y_GRID_SIZE = 30

WIN_WIDTH = X_GRID_SIZE * NUM_X_GRID
WIN_HEIGHT = Y_GRID_SIZE * NUM_Y_GRID
